apiVersion: v1
kind: ConfigMap
metadata:
 name: backendconfigmap
 namespace: rnk-expense-vol
data:
  DB_HOST: mysql-svc
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: rnk-expense-vol
  labels:
    app: backend
    tier: backend
    project: expense-vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense-vol
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense-vol
    spec:
      containers:
      - name: backend
        image: naveenrajoli/backend:1.3
        envFrom:
        - configMapRef:
          name: backendconfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: rnk-expense-vol
spec:
  selector:
    app: backend
    tier: backend
    project: expense-vol
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080



